### ISSUE TITLE
nesting inline tables

### ISSUE THREAD

**Issue by cjztool** [tomj74/chunk-templates#10]
hi bro~   in this page:
http://www.x5software.com/chunk/examples/ChunkExample?example=loop&loc=en_US

example3 template:

 {% loop in $w.related_widgets as $r %}

How to  write related_widgets in inlineTable?

My code is:

Nether

String w = "[ [widget_id,widget_name,related_widgets] , [1, a, [r1, ra] ] , [2,b] , [3, c] ]";
chunk.set("widgets", w);

Nor

String w = "[ [widget_id,widget_name,related_widgets] , [1, a, [ [widget_id,widget_name],[r1, ra] ] ] , [2,b ] , [3, c] ]";
chunk.set("widgets", w);

work well...

**Comment by tomj74** [comment]
Inline tables may not be nested.  The example expects you to use POJOs or nested Map data.

You may provide static nested data in JSON format if you add json-smart to the classpath:

```
{% exec #example_3 @json %}
{ "widgets" : [ { "widget_id" : "1001", "widget_name" : "Hoositwhatsit", "related_widgets" : [ {"widget_id":"1002","widget_name":"Thingamajig"}, {"widget_id":"1003","widget_name":"Gadget"} ] },
                { "widget_id" : "1002", "widget_name" : "Thingamajig" },
                { "widget_id" : "1003", "widget_name" : "Gadget" },
                { "widget_id" : "1004", "widget_name" : "Bauble" },
                { "widget_id" : "1005", "widget_name" : "Bangle" },
              ]
}
{% endexec %}
```

**Comment by cjztool** [comment]
:+1:  Thanks!
^_^
