### ISSUE TITLE
Include another template didn't work

### ISSUE THREAD

**Issue by cjztool** [tomj74/chunk-templates#11]
http://www.x5software.com/chunk/examples/ChunkExample?example=include&loc=en_US

use  chunk-templates-3.1.1.jar

file tree like this:

src
|----themes
        |----ex9.chtml
        |----lorem_ipsum.chtml

in ex9.chtml:

<pre>
a
{% include lorem_ipsum %}
b
</pre>

in lorem_ipsum.chtml:

{#example_1}
<div>
 Earth to {$name}.  Come in, {$name}.
</div>
{#}

Java code:

Theme theme = new Theme();
Chunk c = theme.makeChunk("ex9");
c.set("name", "comeon");
System.out.println(c.toString());

I expect to get:

<pre>
a
<div>
 Earth to comeon.  Come in, comeon.
</div>
b
</pre>

But,,it prints:

<pre>
a

b
</pre>

Did I miss something?

**Comment by tomj74** [comment]
lorem_ipsum refers to the contents of that file *minus* all of the snippet blocks defined in {#snippet}...{#} containers.

Your example will work if you just fully qualify the snippet reference in ex9.chtml like so:

```
a
{% include lorem_ipsum#example_1 %}
b
```

Or, you could also just remove the snippet container tags from lorem_ipsum.chtml so the toplevel template contains what you're looking for:

```
<div>
 Earth to {$name}.  Come in, {$name}.
</div>
```

**Comment by cjztool** [comment]
:+1:  Thanks!
