### ISSUE TITLE
looping through collection of beans with constants is not possible

### ISSUE THREAD

**Issue by harishd84** [tomj74/chunk-templates#12]
I have requirement, where to list the bean's info as list, while rendering the bean which has constants within, is not able to populate the template html. But while rendering the bean alone no issues

Ex: List<MyBean> mybeans = new ArrayList();
      chunk.setToBean("mybeans", mybeans); 
   with the above code if my bean has constants in it, is not working. working if not has constants

Please help me with this issue

**Comment by tomj74** [comment]
confirmed, working on a fix. will release shortly.

**Comment by tomj74** [comment]
please try the new 3.1.2 release, let me know if this fixes it

**Comment by harishd84** [comment]
Thats great, thanks. it worked great
