### ISSUE TITLE
while looping, how can i handle pagination

### ISSUE THREAD

**Issue by harishd84** [tomj74/chunk-templates#13]
while looping through the objects, how can i set counter to start with
Example: i have ten records, first i will get only five and display them with serial number, if i go to next page i get another five records and now i to have start with serial number from 5. Please help me with this

**Comment by tomj74** [comment]
I think pagination logic would have to be handled in the view controller.  Make a new list that's the desired  subset of the full list and pass that list into the chunk.

There is a slice filter for making subsets of lists but it will only take static numbers as arguments.

For example ```{% loop in $list|slice(:5) as $x %}``` would give you the first five and ```{% loop $list|slice(5:10) as $x %}``` could give you the next five but you can't pass a $tag to slice -- eg ```{% loop $list|slice($from:$to) as $x %}``` will not work.  I could maybe add this as a feature but you would still have to set $from and $to in the view controller.

**Comment by tomj74** [comment]
Update: implemented a filter for slicing by page, which takes two args a la ```page(pageNum,pageSize)```
```
{% $list|page($pg, 10) %}
```

This filter will be available in next release.  For example, you could now break a list into rows of five elements each - the outer loop jumps to every fifth element (the third slice arg is a step function), and the inner loop iterates over just the items on each page.
```
{% loop in $x|slice(::5) as $a counter=$pg,1 %}
  Page {$pg}: {% loop in $x|page($pg,5) as $item divider='-'}{$item}{% endloop %}
{% endloop %}
```

If $x is the alphabet, this will output:
```
  Page 1: A-B-C-D-E
  Page 2: F-G-H-I-J
  Page 3: K-L-M-N-O
  Page 4: Q-P-R-S-T
  Page 5: U-V-W-X-Y
  Page 6: Z
```

**Comment by slisznia** [comment]
This sounds great

**Comment by harishd84** [comment]
Thanks for your reply, thats great. But my requirement, i will not load full list at a time, i will first get five records from server, after rendering that, if user intended to go second page, again server request to clear the  same list and fetch next five records put it in same list, now this second time list will contain size

**Comment by harishd84** [comment]
HI,
I created my own custom filter SerialGeneratorFilter works very good, thanks for giving hook to create custom filters

**Comment by tomj74** [comment]
Glad you were able to solve this!
