### ISSUE TITLE
loop item fieldName

### ISSUE THREAD

**Issue by slartus** [tomj74/chunk-templates#20]
in loop items with names like "nameSubname" not replaced. I have to rename to name_subname

not worked:
```
public class Comment {   
    public String userNick;
}
 {% loop in $comments as $item %}
<img class="media-object" alt="{$item.userNick}" title="{$item.userNick}" src="{$item.userAvatar}">
  {% endloop %}

```

worked:
```
public class Comment {   
    public String user_nick;
}

 {% loop in $comments as $item %}
<img class="media-object" alt="{$item.user_nick}" title="{$item.user_nick}" src="{$item.user_avatar}">
  {% endloop %}
```

**Comment by tomj74** [comment]
java attributes undergo a camelCase to snake_case transformation.  The second template will work with the first class.

thanks for the feedback, in the future maybe I will make the transformation optional since it might not be intuitive.

**Comment by slartus** [comment]
ok, thanks
