### ISSUE TITLE
how to get first item from loop and break?

### ISSUE THREAD

**Issue by slartus** [tomj74/chunk-templates#21]

**Comment by tomj74** [comment]
maybe you want to use the "get" filter ``{% $items|get(0) %}`` to access the first item in a list.

**Comment by slartus** [comment]
Thanks again!

**Comment by tomj74** [comment]
or use slice to loop over just the first item:
```
{% loop in $items|slice(0:1) as $item %}
 ...
{% endloop %}
```

**Comment by slartus** [comment]
how to get field of first item? 
$photos|get(0).big ?

**Comment by slartus** [comment]
and how to filter by count of list?
not worked:
{% if ($photos|count>1) %}
{% if ($photos|length>1) %}

**Comment by tomj74** [comment]
```
{% if $photos|length|calc(>1) %}
```

**Comment by tomj74** [comment]
```
{% loop in $photos|slice(0:1) as $photo %}
 {% $photo.big %}
{% endloop %}
```

**Comment by slartus** [comment]
{% loop in $photos|slice(0:1) as $photo %}
 {% $photo.big %}
{% endloop %}

it is a pity that there is no short recording.
but anywhere thanks for your library!

**Comment by tomj74** [comment]
as of 3.2.4 you can now do this:
```
{% $items|get(0).big %}
```
which saves you from having to construct a loop/exec call.
