### ISSUE TITLE
Multiple template processing and filter arguments

### ISSUE THREAD

**Issue by ddvorscak** [tomj74/chunk-templates#23]
I have questions about 2 things:

**FIRST:**
Is it possible with Chunk template to process template multiple times?

Idea is to send template to one program module that will fill template with data that it contains and then pass that partially processed template to some other module to fill its data into template to get final result.

For example if you have some template like:
```
{#example}
Template processed {$times}. Template processed {$second:{$times}}
{#}

```
And send this template to be processed and result is:
`Template processed ONCE. Template processed {$times}`

And then process template again and get final result like:
`Template processed ONCE. Template processed TWO_TIMES.`

This example works but it is not elegant to write it like this nested is there any other way to do it?

**SECOND:**
When creating custom filter is it possible to pass variable as argument not just some hard coded text?

For example if have template like:
`{$data|calculation($on_value,#0.00)}`

where calculation is custom filter and have 2 arguments where first one ($on_value) is some object passed as bean to template same as $data object.

**Comment by tomj74** [comment]
Re: interpolating multiple times -- this is precisely why a tag with no provided value passes through without being interpolated.  If your template is "{$a} {$b} {$c}" and you set a `value` for `a` and `c` then the result is "value {$b} value" which can be passed in as a new template.

Re: variable as argument -- the easiest way to do this is with [backticks](http://www.x5software.com/chunk/wiki/index.php?title=Chunk#Backticks_.28dynamic_tags.29):
```
{$data|calculation(`$on_value`,#0.00)}
```
