### ISSUE TITLE
Android localization

### ISSUE THREAD

**Issue by ddvorscak** [tomj74/chunk-templates#24]
Hi,

I'm looking to add localization to android device. As I know localization should be in structure "/locale/xx_XX/translate-csv", I'm guessing in themeFolder.
I made my own TemplateProvider so I can use templates from external storage not only assets directory.
I set local on Theme but nothing happens. I've been looking trough code a bit and I see that in class ChunkLocale method locateLocaleDB provides translations InputStream. 
I made it work by setting: 
`System.setProperty("chunk.localedb.path","fullPathToMyLocaleDir"); `
before generating template. Just wonder is this good way to go?
Its only way as I see that this method provides good directory path to translation file in Android since no context passed nor full path to locale directory used.

**Comment by tomj74** [comment]
That solutions sounds fine.

The expectation is not for the locale files to be inside the themes folder; by default a server-side app would look for translation files as resources in the classpath root at `/locale/xx_XX/translate.csv` just like it looks for theme files as classpath resources by default in `/themes/...`

To be honest I never thought much about what an appropriate default arrangement / layout would be on Android.  Perhaps there should be a way to provide a custom TranslationsProvider? I'll have to give that some thought but in the meantime it sounds like you have something working.

**Comment by ddvorscak** [comment]
TranslationsProvider idea sounds great and flexible enough.

**Comment by tva-TIS** [comment]
I guess no news on this? If i understand correctly, the current solution would require to write the translation files to the filesystem to use them, which I think would be good to avoid.

**Comment by tomj74** [comment]
how are you expecting to package/provide the translation files?

**Comment by tva-TIS** [comment]
I personally think it would be most convenient, if they could be saved in the assets folder along with the templates, and ChunkLocale would detect that it's running on Android to try to fetch the data from the AssetManager. This however would mean that would need to have given an Instance of Context or AssetManager.

**Comment by tva-TIS** [comment]
Worked around this issue for now by Adding tags with "translate_" prefix. Filling them with values from the translation files even provides locale support. Probably not the way to go for larger templates, but works for now. I'm afraid I probably wouldn't have the time to implement a solution for this issue on my own.

**Comment by tomj74** [comment]
finally addressed this with recent 3.6.0 release
