### ISSUE TITLE
final public attributes not accessible

### ISSUE THREAD

**Issue by slisznia** [tomj74/chunk-templates#27]
This renders when referred to in a template (ie $test_me)
`class MyClass {
  public String testMe;
}`

This does not render:
`class MyClass {
  public final String testMe;
}
`

Spent a few hours to determine that.. ):

**Comment by tomj74** [comment]
Thanks for reporting this.  I'll add to the test suite and release a patch this week if there is an easy fix.

**Comment by slisznia** [comment]
The class in the ticket was a simplistic example - in reality there are a few final fields.

I resolved the conflict by removing final qualifiers - I didn't like that since it was an immutable class before - but oh well. Breaking backwards compatibility is a hard decision so naturally I don't want to push you in that direction. Personally for me, this "bug" has proven annoying to track down, perhaps more so because I don't write new chunk-code/templates very often. Perhaps giving the option to annotate the class to tell the chunk it's not a bean would work.

**Comment by tomj74** [comment]
I like the annotation idea, will explore.

**Comment by tomj74** [comment]
added @AccessAsPojo and @AccessAsBean annotations per your suggestion and released a new version, available in 3.4.0+

**Comment by slisznia** [comment]
Thanks!
