### ISSUE TITLE
Error handling in production

### ISSUE THREAD

**Issue by slisznia** [tomj74/chunk-templates#28]
When the system is deployed to production, we want Chunk to throw an exception on any error like "Template not found". This is important as currently, for example, we may email our customers an error message instead of having the system fail and let us correct it first. This is specially important for network template provider as the template may be missing for a variety of external reasons.

**Comment by tomj74** [comment]
agree, this seems like a valuable feature.  I will try to implement this week and do a release.

**Comment by tomj74** [comment]
ok, released 3.5.0

when making your theme, be sure to set
```
theme.setAbortOnMissingTemplate(true);
```

and you can catch a new runtime exception: `TemplateNotFoundException`

**Comment by slisznia** [comment]
How long before Maven gets updated? Still points at 3.4.0
https://mvnrepository.com/artifact/com.x5dev/chunk-templates

**Comment by slisznia** [comment]
Works perfect, thanks Tom!
