### ISSUE TITLE
Cannot compile sourcecode for Java not Android

### ISSUE THREAD

**Issue by EAG-es** [tomj74/chunk-templates#30]
Hi.

I have a dependency in package: com.x5.template.providers, file: AndroidTemplates.java
The error is:
import android.content.Context;

package does not exist.

Should I remove the file?
Does it affect a project with common code Java & Android?

**Comment by tomj74** [comment]
Why do you need to compile chunk from sources?

Are you not able to use the [released jars](https://github.com/tomj74/chunk-templates/releases)?

**Comment by EAG-es** [comment]
Thanks for your answer.
The reason I try to compile source code is for warrant  maintainability, if discontinued...
Some source codes are so complex to build that I prefer not include them in projects...
