### ISSUE TITLE
Bean's property doesn't work.

### ISSUE THREAD

**Issue by Alexander-Greckov** [tomj74/chunk-templates#31]
I followed this tutorial and I still can't fetch the bean value.
I event annotated my class with @AccessAsBean and it still doesn't work.
I used this on Android

**Comment by tomj74** [comment]
Were you able to resolve this?  I have not tested chunk on recent versions of android, I'd be interested to hear if there is an issue.

**Comment by Alexander-Greckov** [comment]
Everything is fine, and because of this reason I closed this issue, probably i named my methods incorrectly
