### ISSUE TITLE
Android Bean Getter NullPointerException

### ISSUE THREAD

**Issue by bravo-delta** [tomj74/chunk-templates#32]
I'm experiencing a NullPointerException whenever the MadRobotIntrospector in ObjectDataMap tries to copy the properties into the Hashtable.

It happens if a Bean also contains Setters. In this case the property.getReadMethod() returns null for the Setters and the call to getter.invoke(bean, (Object[])null); crashes in the next line.
[ObjectDataMap.java#L571](https://github.com/tomj74/chunk-templates/blob/master/src/main/java/com/x5/util/ObjectDataMap.java#L571)

This seems to be handled correctly for the non Android version [ObjectDataMap.java#L521](https://github.com/tomj74/chunk-templates/blob/master/src/main/java/com/x5/util/ObjectDataMap.java#L521)
Here a null check makes sure that only Getters are processed.

**Comment by tomj74** [comment]
thanks, will be fixed in 3.6.0 release
