### ISSUE TITLE
Question: how to iterate the root?

### ISSUE THREAD

**Issue by agilepro** [tomj74/chunk-templates#34]
I am used to using this kind of expression:

**{% loop in $main as $key:$value %}**

and it works great!   This iterates an object (map) at the location of "main" giving all the keys and values of the object that is at the location "main" in the overall data structure.

But how do I iterate the key/values of the root data structure?   I just don't know how to address the root object since it does not have a name.

**Comment by tomj74** [comment]
The closest thing is the debug function {% tagStack %} which dumps all keys in the stack at a particular evaluation point in the template.  But, just keys, no values, and no way to loop through that.

If I were you I would simply pass all data to the template in a toplevel "root" object (or something short like "vm" so you don't mind typing it over and over in the tempalte).  By pushing everything down one level, you'll effectively have access to a root object that you can loop over.

**Comment by tomj74** [comment]
so, I was monkeying around and discovered that you can use a combination of filters and backticks with tagStack and pull this rabbit out of the hat.
```
{% loop in .tagStack|split|slice(2:) as $key %}
{$key} - {$`$key|slice(1)`}
{% endloop %}
```
since tagStack includes ALL template tags including root level and deeper, you may need to apply some additional filtering.

**Comment by agilepro** [comment]
Thanks Tom!   That is great.

Possible feature would be to make this work:

{% loop in $ as $key:$value %}

But not important, especially if it makes it hard to catch syntax errors.
