### ISSUE TITLE
Moving away from Json-smart

### ISSUE THREAD

**Issue by oscerd** [tomj74/chunk-templates#37]
Hello,

in Apache Camel we are using the chunk template library in one of the components we are supporting: https://github.com/apache/camel/tree/master/components/camel-chunk

The chunk templates library is currently using json-smart 1.1.1 as compile dependency. Json-smart seems to be dead and there are opened issues with some important problem. 

https://github.com/netplex/json-smart-v1/issues/7
and the same for version 2.x

There doesn't seem to be activity on the project, so this issue won't be fixed in short time. Is there any idea of moving away from json-smart for using something else?

**Comment by tomj74** [comment]
Well that's no good.  I will make json-smart an optional dependency in the next release and also support jackson-databind as an alternate way to enable json features.

**Comment by oscerd** [comment]
Thanks a lot for your feedback.

**Comment by tomj74** [comment]
Done!  Update to 3.6.1 to be free of the transitive dependency.

**Comment by oscerd** [comment]
Thanks.
