### ISSUE TITLE
in android  ,property case different  is not working 

### ISSUE THREAD

**Issue by yang0000meng** [tomj74/chunk-templates#38]
template

    {% loop in $tvlist as $list %}
    {$list.listname} <br>
    {$list.ListName}<br>
    {$list}<br>
    {% endloop %}

the not working  class  

    @AccessAsBean
    @AccessAsPojo
    public class Info {

        private String ListName;
        public  String getListName()
        {
            return ListName;
        }
        public  void setListName(String value)
        {
            ListName = value;
        }
    }

the working  class  

    public class Info {

        private String ListName;
        public  String getListname()
        {
            return ListName;
        }
        public  void setListname(String value)
        {
            ListName = value;
        }
    }

the  different is  getListname() and  getListName()

when has two upper letters is not working

**Comment by tomj74** [comment]
CamelCase is converted to snake_case so the field is probably exposed as list_name

will test and confirm
