### ISSUE TITLE
If with infix && generating different results based on order of tests a && b vs b && a

### ISSUE THREAD

**Issue by JaredDavis22** [tomj74/chunk-templates#41]
Hi,

I think I found a case where order of tests in an if statement produce different results. Perhaps I'm messing up the ()?

given:
a evaluates to true
b evaluates to true

a && b fails while b && a works. I expected order to not matter.

Template:
{#test}
A={$a}
B={$b}
is A? {%if ($a) } True {% endif %}
is B != 0.0 ? {%if ($b != 0.0) %} True {% endif %}
is B 1 ? {%if ($b == 1) %} True {% endif %}
try a b 0 {%if ($a) && ($b != 0.0) %} True {% endif %}
try b a 0 {%if ($b != 0.0) && ($a) %} True {% endif %}
try a b 1 {%if ($a) && ($b == 1) %} True {% endif %}
try b a 1 {%if ($b == 1) && ($a) %} True {% endif %}
end of test
{#}

Expecting all to be True, not half (Eddie...odd movie reference)

pre
A=a
B=1
is A?  True 
is B != 0.0 ?  True 
is B 1 ?  True 
try a b 0 
try b a 0  True 
try a b 1 
try b a 1  True 
end of test

post

java code

        Chunk chunk = theme.makeChunk(CHUNKTEMPLATE + "#test");
        chunk.set("a","a");
        chunk.set("b", "1");
        System.out.println("pre");
        System.out.println(chunk.toString());
        System.out.println("post");

**Comment by tomj74** [comment]
unfortunately, there is no support for parens as logical grouping in the conditional expressions.  surrounding the entire expr in parens is optional, and it will strip those outer parens away.

**Comment by JaredDavis22** [comment]
Thanks. I've never used ANTLR. Doing the grammar looks like it may take a while.

I took away the parens. I see it is throwing an exception to the output but not throwing it to the caller.

is A?       {%if $a } True {% endif %}
is B != 0.0 {%if $b != 0.0 %} True {% endif %}
is B 1 ?    {%if $b == 1 %} True {% endif %}
try a b 0   {%if $a && $b != 0.0 %} True {% endif %}

com.x5.template.InvalidExpressionException: Missing infix operator between expressions
	at com.x5.template.CondTree.buildBranch(CondTree.java:49)
	at com.x5.template.CondLexer.parse(CondLexer.java:27)
	at com.x5.template.IfTag.isTrueExpr(IfTag.java:207)
	at com.x5.template.IfTag.renderBlock(IfTag.java:221)
	at com.x5.template.SnippetBlockTag.render(SnippetBlockTag.java:46)
	at com.x5.template.Snippet.render(Snippet.java:842)
	at com.x5.template.Chunk.explodeToPrinter(Chunk.java:743)
	at com.x5.template.Chunk.renderForParentToPrinter(Chunk.java:704)
	at com.x5.template.Chunk.explodeForParentToPrinter(Chunk.java:696)
	at com.x5.template.Chunk.render(Chunk.java:658)
	at com.x5.template.Chunk.toString(Chunk.java:627)

**Comment by tomj74** [comment]
yikes.  ok there might be a way to patch this up.  thanks for the heads up, I will add a couple new tests and try to see what's going sideways.  I see this in the docs so perhaps I misremembered about the parens:

> Starting in 3.3.0, conditional expressions may be grouped with parens and joined using || and && operators.

**Comment by JaredDavis22** [comment]
It makes sense w/o the parens.

Left to right

if $a && $b != 0.0 

$a && $b   then the leftover != 0.0

**Comment by tomj74** [comment]
found bug and fixed.  will release a patch ver soon.

**Comment by tomj74** [comment]
3.6.2 released.  should fix these conditional expression parsing issues.  let me know if you spot any outstanding issues.
