### ISSUE TITLE
Loop a map?

### ISSUE THREAD

**Issue by newlarry** [tomj74/chunk-templates#9]
I can loop in a java.util.Map passed directly to Chunk like this:

  {% loop in $map as $key:value %}

But I can't loop in a child object like this:

  {% loop in $object.map as $key:value %}

Can Chunk do this? I get strange behavior.

**Comment by tomj74** [comment]
probably a bug, I will investigate and issue a patch release if I can track it down.

**Comment by tomj74** [comment]
this is now fixed in 3.0.2 -- please upgrade and give it a try!

**Comment by newlarry** [comment]
Whoa, thanks Tom! Working nicely.
